name: Run Shell Script

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Shell Script
      run: |
        chmod 755 script.sh
        ./script.sh
